name: check-latest-dd-release

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: install python packages
        run: |
          python3.9 -m pip install --upgrade pip
          pip3.9 install requests

      - name: execute py script
        run: python3.9 check_DD_agent_release.py

